# Configuration pour environnement local XAMPP/MySQL
spring:
  application:
    name: project-management
  
  # Configuration de la base de données MySQL (XAMPP)
  datasource:
    url: jdbc:mysql://localhost:3306/nsia_project_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Configuration JPA/Hibernate pour MySQL
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false

# Configuration du serveur
server:
  port: 8080
  servlet:
    context-path: /nsia

# Configuration des logs
logging:
  level:
    com.projectmanagement: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application-local.log

# Configuration JWT (pour tests locaux)
jwt:
  secret: LocalTestSecretKeyForJWTTokenGenerationAndValidation2024
  expiration: 86400000

# Configuration des uploads
file:
  upload-dir: ./uploads/documents
  
# Configuration CORS pour développement local
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Configuration de développement
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always