# Configuration Oracle pour environnement de test
spring:
  application:
    name: project-management-oracle-test
  
  # Configuration DataSource Oracle
  datasource:
    url: ${ORACLE_DB_URL:jdbc:oracle:thin:@//localhost:1521/XE}
    username: ${ORACLE_DB_USERNAME:project_user}
    password: ${ORACLE_DB_PASSWORD:secret}
    driver-class-name: oracle.jdbc.OracleDriver
    
    # Configuration HikariCP pour Oracle
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: ProjectOraclePool
      validation-timeout: 3000
      connection-test-query: SELECT 1 FROM DUAL
  
  # Configuration JPA/Hibernate pour Oracle
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        show_sql: ${HIBERNATE_SHOW_SQL:false}
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
        use_sql_comments: false
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
    open-in-view: false

# Configuration serveur
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /nsia
  compression:
    enabled: true
    min-response-size: 1024

# Configuration logging pour test
logging:
  level:
    com.projectmanagement: ${LOG_LEVEL_APP:INFO}
    org.springframework: ${LOG_LEVEL_SPRING:WARN}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_SQL_PARAMS:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:/var/log/nsia/project-management-test.log}

# Configuration management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized

# Configuration spécifique à l'environnement de test
app:
  environment: oracle-test
  features:
    audit-enabled: true
    export-enabled: true
    kpi-calculation-enabled: true
  security:
    jwt:
      secret: ${JWT_SECRET:test-secret-key-change-in-production}
      expiration: ${JWT_EXPIRATION:86400000}
  export:
    max-records: ${EXPORT_MAX_RECORDS:10000}
    timeout-seconds: ${EXPORT_TIMEOUT:300}